import type { Bed, Flat, Payment, Room, Tenant } from '@/types';

export const flats: Flat[] = [
  {
    id: 'f1',
    name: 'Sunrise PG',
    address: '12 MG Road, Koramangala, Bangalore',
    totalRooms: 8,
    totalBeds: 16,
    occupiedBeds: 14,
    vacantBeds: 2,
  },
  {
    id: 'f2',
    name: 'Green Valley',
    address: '45 5th Block, HSR Layout, Bangalore',
    totalRooms: 8,
    totalBeds: 16,
    occupiedBeds: 12,
    vacantBeds: 4,
  },
  {
    id: 'f3',
    name: 'City Heights',
    address: '88 Indiranagar, Bangalore',
    totalRooms: 8,
    totalBeds: 16,
    occupiedBeds: 13,
    vacantBeds: 3,
  },
];

export const rooms: Room[] = [
  { id: 'r1', flatId: 'f1', flatName: 'Sunrise PG', roomNumber: '101', totalBeds: 2, occupiedBeds: 2, vacantBeds: 0 },
  { id: 'r2', flatId: 'f1', flatName: 'Sunrise PG', roomNumber: '102', totalBeds: 2, occupiedBeds: 2, vacantBeds: 0 },
  { id: 'r3', flatId: 'f1', flatName: 'Sunrise PG', roomNumber: '103', totalBeds: 2, occupiedBeds: 1, vacantBeds: 1 },
  { id: 'r4', flatId: 'f2', flatName: 'Green Valley', roomNumber: '201', totalBeds: 2, occupiedBeds: 2, vacantBeds: 0 },
  { id: 'r5', flatId: 'f2', flatName: 'Green Valley', roomNumber: '202', totalBeds: 2, occupiedBeds: 1, vacantBeds: 1 },
  { id: 'r6', flatId: 'f3', flatName: 'City Heights', roomNumber: '301', totalBeds: 2, occupiedBeds: 2, vacantBeds: 0 },
  { id: 'r7', flatId: 'f3', flatName: 'City Heights', roomNumber: '302', totalBeds: 2, occupiedBeds: 2, vacantBeds: 0 },
  { id: 'r8', flatId: 'f3', flatName: 'City Heights', roomNumber: '303', totalBeds: 2, occupiedBeds: 1, vacantBeds: 1 },
];

export const beds: Bed[] = [
  { id: 'b1', bedId: 'SUN-101-A', flatId: 'f1', flatName: 'Sunrise PG', roomId: 'r1', roomNumber: '101', rentAmount: 9500, status: 'occupied', tenantId: 't1', tenantName: 'Rahul Sharma' },
  { id: 'b2', bedId: 'SUN-101-B', flatId: 'f1', flatName: 'Sunrise PG', roomId: 'r1', roomNumber: '101', rentAmount: 9500, status: 'occupied', tenantId: 't2', tenantName: 'Priya Patel' },
  { id: 'b3', bedId: 'SUN-103-A', flatId: 'f1', flatName: 'Sunrise PG', roomId: 'r3', roomNumber: '103', rentAmount: 9000, status: 'vacant' },
  { id: 'b4', bedId: 'GV-201-A', flatId: 'f2', flatName: 'Green Valley', roomId: 'r4', roomNumber: '201', rentAmount: 8500, status: 'occupied', tenantId: 't3', tenantName: 'Amit Kumar' },
  { id: 'b5', bedId: 'GV-202-B', flatId: 'f2', flatName: 'Green Valley', roomId: 'r5', roomNumber: '202', rentAmount: 8500, status: 'vacant' },
  { id: 'b6', bedId: 'CH-301-A', flatId: 'f3', flatName: 'City Heights', roomId: 'r6', roomNumber: '301', rentAmount: 10000, status: 'occupied', tenantId: 't4', tenantName: 'Sneha Reddy' },
  { id: 'b7', bedId: 'CH-303-B', flatId: 'f3', flatName: 'City Heights', roomId: 'r8', roomNumber: '303', rentAmount: 10000, status: 'maintenance' },
  { id: 'b8', bedId: 'CH-302-A', flatId: 'f3', flatName: 'City Heights', roomId: 'r7', roomNumber: '302', rentAmount: 10000, status: 'occupied', tenantId: 't5', tenantName: 'Vikram Singh' },
];

export const tenants: Tenant[] = [
  {
    id: 't1',
    name: 'Rahul Sharma',
    phone: '+91 98765 43210',
    aadhaar: 'XXXX-XXXX-1234',
    joiningDate: '2024-08-15',
    dueDate: '2026-06-05',
    assignedBedId: 'b1',
    assignedBedLabel: 'SUN-101-A',
    flatName: 'Sunrise PG',
    rentAmount: 9500,
    deposit: 19000,
    paymentStatus: 'paid',
    email: 'rahul@email.com',
    notes: 'Prefers ground floor. Vegetarian.',
  },
  {
    id: 't2',
    name: 'Priya Patel',
    phone: '+91 91234 56789',
    aadhaar: 'XXXX-XXXX-5678',
    joiningDate: '2024-11-01',
    dueDate: '2026-06-01',
    assignedBedId: 'b2',
    assignedBedLabel: 'SUN-101-B',
    flatName: 'Sunrise PG',
    rentAmount: 9500,
    deposit: 19000,
    paymentStatus: 'paid',
  },
  {
    id: 't3',
    name: 'Amit Kumar',
    phone: '+91 99887 76655',
    aadhaar: 'XXXX-XXXX-9012',
    joiningDate: '2025-01-10',
    dueDate: '2026-05-28',
    assignedBedId: 'b4',
    assignedBedLabel: 'GV-201-A',
    flatName: 'Green Valley',
    rentAmount: 8500,
    deposit: 17000,
    paymentStatus: 'overdue',
    notes: 'Payment reminder sent twice.',
  },
  {
    id: 't4',
    name: 'Sneha Reddy',
    phone: '+91 97654 32109',
    aadhaar: 'XXXX-XXXX-3456',
    joiningDate: '2025-03-20',
    dueDate: '2026-06-10',
    assignedBedId: 'b6',
    assignedBedLabel: 'CH-301-A',
    flatName: 'City Heights',
    rentAmount: 10000,
    deposit: 20000,
    paymentStatus: 'pending',
  },
  {
    id: 't5',
    name: 'Vikram Singh',
    phone: '+91 90123 45678',
    aadhaar: 'XXXX-XXXX-7890',
    joiningDate: '2024-06-01',
    dueDate: '2026-06-15',
    assignedBedId: 'b8',
    assignedBedLabel: 'CH-302-A',
    flatName: 'City Heights',
    rentAmount: 10000,
    deposit: 20000,
    paymentStatus: 'partial',
    notes: 'Paid ₹5,000 of ₹10,000 for May.',
  },
  {
    id: 't6',
    name: 'Ananya Iyer',
    phone: '+91 93456 78901',
    aadhaar: 'XXXX-XXXX-2345',
    joiningDate: '2025-04-01',
    dueDate: '2026-06-08',
    assignedBedId: '',
    assignedBedLabel: 'Unassigned',
    flatName: '—',
    rentAmount: 0,
    deposit: 0,
    paymentStatus: 'pending',
  },
];

export const payments: Payment[] = [
  { id: 'p1', tenantId: 't1', tenantName: 'Rahul Sharma', amount: 9500, dueDate: '2026-05-05', paidDate: '2026-05-03', status: 'paid', paymentMode: 'UPI', flatName: 'Sunrise PG' },
  { id: 'p2', tenantId: 't2', tenantName: 'Priya Patel', amount: 9500, dueDate: '2026-06-01', paidDate: '2026-05-30', status: 'paid', paymentMode: 'Bank Transfer', flatName: 'Sunrise PG' },
  { id: 'p3', tenantId: 't3', tenantName: 'Amit Kumar', amount: 8500, dueDate: '2026-05-28', status: 'overdue', flatName: 'Green Valley' },
  { id: 'p4', tenantId: 't4', tenantName: 'Sneha Reddy', amount: 10000, dueDate: '2026-06-10', status: 'pending', flatName: 'City Heights' },
  { id: 'p5', tenantId: 't5', tenantName: 'Vikram Singh', amount: 10000, dueDate: '2026-06-15', paidDate: '2026-05-12', status: 'partial', paymentMode: 'Cash', flatName: 'City Heights' },
  { id: 'p6', tenantId: 't1', tenantName: 'Rahul Sharma', amount: 9500, dueDate: '2026-04-05', paidDate: '2026-04-04', status: 'paid', paymentMode: 'UPI', flatName: 'Sunrise PG' },
  { id: 'p7', tenantId: 't3', tenantName: 'Amit Kumar', amount: 8500, dueDate: '2026-04-28', status: 'overdue', flatName: 'Green Valley' },
];
